version: '3.8'

services:
  # Reverse Proxy con SSL
  traefik:
    image: traefik:v2.10
    container_name: traefik-proxy
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=admin@saider.dev"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - odoo-network
    restart: unless-stopped

  # Base de datos PostgreSQL
  postgresql:
    image: bitnami/postgresql:16
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - TZ=America/Bogota
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./postgresql/backups:/backups
    networks:
      - odoo-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G

  # Servidor Odoo
  odoo:
    image: odoo:latest
    container_name: odoo-app
    depends_on:
      - postgresql
    environment:
      - HOST=postgresql
      - USER=odoo
      - PASSWORD=odoo
      - DEFAULT_LANG=es_PA
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo.rule=Host(`odoo.saider.dev`)"
      - "traefik.http.routers.odoo.entrypoints=websecure"
      - "traefik.http.routers.odoo.tls.certresolver=le"
      - "traefik.http.services.odoo.loadbalancer.server.port=8069"
    networks:
      - odoo-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

# Configuración de redes y volúmenes
volumes:
  postgres_data:
    driver: local
  odoo_data:
    driver: local

networks:
  odoo-network:
    driver: bridge
    attachable: true