services:
  # PostgreSQL
  postgresql:
    image: bitnami/postgresql:latest
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - TZ=America/Bogota
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./postgresql/backups:/backups # Directorio para backups
    networks:
      - odoo-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G

  # Odoo
  odoo:
    image: odoo:latest
    container_name: odoo-app
    depends_on:
      - postgresql
    environment:
      - HOST=postgresql
      - USER=odoo
      - PASSWORD=odoo
      - DEFAULT_LANG=es_PA
      - ODOO_URI=/
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
    networks:
      - odoo-network
    ports:
      - "80:8069"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 4G

volumes:
  postgres_data:
    driver: local
  odoo_data:
    driver: local

networks:
  odoo-network:
    driver: bridge
    attachable: true