services:
  # PostgreSQL
  postgresql:
    image: bitnami/postgresql:latest
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - TZ=America/Bogota
    volumes:
      - postgres_data:/bitnami/postgresql
      - ./postgresql/backups:/backups # Directorio para backups
    networks:
      - odoo-network
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 2G

  # Odoo
  odoo:
    image: odoo:latest
    container_name: odoo-app
    depends_on:
      - postgresql
    environment:
      - HOST=postgresql
      - USER=odoo
      - PASSWORD=odoo
      - DEFAULT_LANG=es_PA
      - VIRTUAL_HOST=odoo.saider.dev    
      - LETSENCRYPT_HOST=odoo.saider.dev  
      - LETSENCRYPT_EMAIL=sebasmoraresu@gmail.com
      - ODOO_URI=/odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
    networks:
      - odoo-network
    expose:
      - "8069"           # Expone el puerto solo en la red interna
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 4G
  
  # NGINX
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - odoo-network
    restart: unless-stopped
    environment:
      - SSL_POLICY=Mozilla-Intermediate
      - FORCE_SSL=true
      - DEFAULT_HOST=odoo.saider.dev
      - VIRTUAL_PATH=/
      - VIRTUAL_PROTO=http
      - PROXY_REVERSE_HOST=on
  
  # LetsEncrypt
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - odoo-network
    environment:
      - DEFAULT_EMAIL=sebasmoraresu@gmail.com
      - ACME_TLS=true
      - DEBUG=true
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  odoo_data:
    driver: local
  certs:
  vhost:
  html:

networks:
  odoo-network:
    driver: bridge
    attachable: true
